### ISSUE TITLE
Generate tokens without expiry

### ISSUE THREAD

**Issue by sksk571** [Cysharp/LitJWT#20]
Expiry isa mandatory parameter of the Encode method and it causes "exp" claim to be automatically inserted into a token. In our case we want to generate tokens without the expiry and also want to keep token as short as possible. Is it possible to add a method overload that generates tokens without expiry?

**Comment by neuecc** [comment]
We feel that no expiry is a risky option, so we will not allow it to be easily added (e.g., overloaded).

**Comment by seanm-fathomhq** [comment]
And yet according to spec, the "exp" field is not required:

> The "exp" (expiration time) claim identifies the expiration time on or after which the JWT MUST NOT be accepted for processing.  The processing of the "exp" claim requires that the current date/time MUST be before the expiration date/time listed in the "exp" claim.   Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew.  Its value MUST be a number containing a NumericDate value.  **Use of this claim is OPTIONAL.**
> https://www.rfc-editor.org/rfc/rfc7519#section-4.1.4
